name: Bundle

on:
  push: # Choose the branch that matches the Smalltalk version below
    branches:
      - squeak-trunk
      # - squeak-6.0
      # - squeak-5.3
      # - squeak-5.2
    paths-ignore: # Skip changes in documentation artifacts
      - '**.md'
      - 'release-notes/**'
  pull_request: # Choose the branch that matches the Smalltalk version below
    branches:
      - squeak-trunk
      # - squeak-6.0
      # - squeak-5.3
      # - squeak-5.2
    paths-ignore: # Skip changes in documentation artifacts
      - '**.md'
      - 'release-notes/**'
  schedule:
    - cron: '0 0 * * *' # Build everyday at midnight
  workflow_dispatch:
    inputs:
      osvm-build:
        description: "Build with latest-build OSVM (i.e., YYYYMMDDHHMM tag). Leave empty for using current OSVM release."
        required: false # if empty, use default VM from files.squeak.org/base
        default: ''

jobs:
  prepare-image:
    strategy:
      fail-fast: true
      matrix:
        smalltalk:
          - Squeak-trunk
          - Squeak64-trunk
          # - Squeak-6.0
          # - Squeak64-6.0
          # - Squeak-5.3
          # - Squeak64-5.3
          # - Squeak-5.2
          # - Squeak64-5.2
          # - Etoys-trunk
          # - Etoys64-trunk
    runs-on: windows-latest
    name: 🛠 Prepare image for ${{ matrix.smalltalk }}
    env:
      SMALLTALK_VERSION: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare image
        shell: bash
        run: ./prepare_image.sh
        timeout-minutes: 20

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.smalltalk }}
          path: |
            tmp/*.sources
            tmp/*.image
            tmp/*.changes

      - name: Export global environment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.smalltalk }}-env
          path: tmp/global-env


  test-image:
    needs: [prepare-image]
    strategy:
      fail-fast: false
      matrix:
        smalltalk:
          - Squeak-trunk
          - Squeak64-trunk
          # - Squeak-6.0
          # - Squeak64-6.0
          # - Squeak-5.3
          # - Squeak64-5.3
          # - Squeak-5.2
          # - Squeak64-5.2
          # - Etoys-trunk
          # - Etoys64-trunk
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          # no 32-bit support on macOS
          - smalltalk: Squeak-trunk
            os: macos-latest
        include:
          - smalltalk: Squeak64-trunk
            os: macos-latest
            extra: '-installer-smoke'
          - smalltalk: Squeak64-trunk
            os: ubuntu-latest
            extra: '-installer-smoke'
          - smalltalk: Squeak64-trunk
            os: windows-latest
            extra: '-installer-smoke'
    runs-on: ${{ matrix.os }}
    name: 🧪 Test image of ${{ matrix.smalltalk }}${{ matrix.extra }} on ${{ matrix.os }}
    env:
      SMALLTALK_VERSION: ${{ matrix.smalltalk }}
      SMALLTALK_CI_CONFIG: ${{ matrix.smalltalk }}${{ matrix.extra }}
    steps:
      - uses: actions/checkout@v2

      - name: Import global environment
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.smalltalk }}-env
          path: tmp

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.smalltalk }}
          path: tmp

      - name: Set up SmalltalkCI
        # uses: hpi-swa/setup-smalltalkCI@v1
        uses: LinqLover/setup-smalltalkCI@marceltaeumel/install-path
        with:
          smalltalk-image: ${{ matrix.smalltalk }}

      - name: Run tests
        continue-on-error: true
        shell: bash
        run: ./test_image.sh
        timeout-minutes: 20
      
      - name: Check whether tests were performed correctly
        shell: bash
        run: |
          if ! compgen -G "tmp/*.xml" > /dev/null; then
            echo "Error: No test result XML files found. Tests may not have been performed correctly."
            exit 1
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.smalltalk }}-tests
          path: tmp/*.xml # smalltalkCI test results


  prepare-bundles:
    needs: [prepare-image]
    strategy:
      fail-fast: false # Maybe make deployment extra job?
      matrix:
        smalltalk:
          - Squeak-trunk
          - Squeak64-trunk
          # - Squeak-6.0
          # - Squeak64-6.0
          # - Squeak-5.3
          # - Squeak64-5.3
          # - Squeak-5.2
          # - Squeak64-5.2
          # - Etoys-trunk
          # - Etoys64-trunk
    runs-on: macos-14 # macos-13 had issues with hdutil
    name: 📦 Prepare bundles for ${{ matrix.smalltalk }}
    env:
      SMALLTALK_VERSION: ${{ matrix.smalltalk }}
      SHOULD_DEPLOY: ${{ endsWith(github.ref, 'squeak-trunk') && github.event.inputs.osvm-build == '' }}
      SHOULD_CODESIGN: ${{ endsWith(github.ref, 'squeak-trunk') }}
      VM_RC_TAG: ${{ github.event.inputs.osvm-build }} # only workflow-dispatch; otherwise, use VM from files.squeak.org/base that fits ${{ matrix.smalltalk }}

    steps:
      - uses: actions/checkout@v2

      - name: Import global environment
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.smalltalk }}-env
          path: tmp

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.smalltalk }}
          path: tmp

      - run: ./prepare_bundles.sh
        env:
          CODESIGN_KEY: ${{ secrets.CODESIGN_KEY }}
          CODESIGN_IV: ${{ secrets.CODESIGN_IV }}
          CERT_IDENTITY: ${{ secrets.CERT_IDENTITY }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          NOTARIZATION_USER: ${{ secrets.NOTARIZATION_USER }}
          NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.smalltalk }}-bundles
          path: product/*

      - run: ./deploy_bundles.sh
        if: env.SHOULD_DEPLOY == 'true'
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_IV: ${{ secrets.DEPLOY_IV }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          PROXY_PORT: ${{ secrets.PROXY_PORT }}
          PROXY_HOST: ${{ secrets.PROXY_HOST }}
          PROXY_USER: ${{ secrets.PROXY_USER }}
          UPSTREAM_HOST: ${{ secrets.UPSTREAM_HOST }}
          UPSTREAM_USER: ${{ secrets.UPSTREAM_USER }}

      - name: Update artifact in custom-osvm-bundle
        uses: ncipollo/release-action@v1
        if: env.SHOULD_DEPLOY == 'false' # only if not uploaded to file.squeak.org
        with:
          prerelease: true # release candidate
          allowUpdates: true
          replacesArtifacts: true
          artifacts: product/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'custom-osvm-bundle'
          body: ${{ github.event.head_commit.message }}
